name: NPM Release Automation
on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'The library release version'
        required: true
        default: ''
      
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          token: ${{ secrets.PAT }}
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20
          registry-url: "https://registry.npmjs.org/"

      - name: Update package.json version
        run: |
          VERSION="${{ github.event.inputs.environment }}"
          echo "Release v  $VERSION"
          jq --arg ver "$VERSION" '.version = $ver' package.json > temp.json && mv temp.json package.json
          jq --arg ver "$VERSION" '.version = $ver' modules/cmpapi/package.json > temp.json && mv temp.json modules/cmpapi/package.json
          jq --arg ver "$VERSION" '.version = $ver' modules/stub/package.json > temp.json && mv temp.json modules/stub/package.json
      - name: Check input version TAG
        run: |
          git status
          VERSION="${{ github.event.inputs.environment }}"
          echo "Release v  $VERSION"
          if git show-ref --tags --verify --quiet "refs/tags/${VERSION}"; then
            echo "Tag ${VERSION} exists"
            echo "version_changed=false" >> $env:GITHUB_OUTPUT
          else
            echo "Tag ${VERSION} does not exist"
            echo "version_changed=true" >> $env:GITHUB_OUTPUT
          fi
      - name: Publish to NPM
        if: ${{steps.check.outputs.version_changed == 'true'}}
        run: | 
          npm --version
          cd modules/stub
          pwd
          cd ../cmpapi
          pwd
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
      - name: Commit and Push Changes
        if: ${{steps.check.outputs.version_changed == 'true'}}
        run: |
          VERSION="${{ github.event.inputs.environment }}"
          echo "version $VERSION"
          gh release list
        env:
          GITHUB_TOKEN: ${{secrets.PAT}}
